dist: trusty

language: node_js
node_js:
  - 'stable'

branches:
  only:
    - master

addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable

cache:
  directories:
    - ./node_modules

install:
  - npm install

cache: npm

script:
  - npm run lint
  - npm run test
