dist: trusty
sudo: required
language: node_js
node_js:
  - '12'

branches:
  only:
    - master

addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable

before_install:
- export CHROME_BIN=chromium-browser
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start

cache: npm

cache:
  directories:
    - ./node_modules

before_script:
  - npm install

jobs:
  include:
  - stage: lint
    script:
    - ng lint
  - stage: test
    script:
    - npm run test:lib
  - stage: build
    script:
    - npm run build:lib
